### ISSUE TITLE
上传商品图片失败

### ISSUE THREAD

**Issue by saberma** [saberma/shopqi#194]
商品没有任何图片时，上传图片前台直接报错

``` ruby
The error occurred while evaluating nil.+

app/controllers/admin/photos_controller.rb:19:in `create'
```

删除图片时后台报错

``` ruby
Rendered admin/photos/destroy.js.haml (6.4ms)
Completed 500 Internal Server Error in 125ms

ActionView::Template::Error (Missing partial products/upload_photos with {:handlers=>[:erb, :builder, :arb, :coffee, :haml], :formats=>[:js, :html], :locale=>[:cn, :cn]}. Searched in:
  * "/home/saberma/Documents/shopqi/app/views"
  * "/home/saberma/.rvm/gems/ruby-1.9.3-rc1/gems/activeadmin-0.3.2/app/views"
  * "/home/saberma/.rvm/gems/ruby-1.9.3-rc1/gems/kaminari-0.12.4/app/views"
  * "/home/saberma/.rvm/gems/ruby-1.9.3-rc1/gems/devise-1.4.7/app/views"
):
    1: $("#image-show-area").html("#{escape_javascript(render partial:'products/upload_photos',locals:{product: product})}" );
    2: msg('#{flash[:notice]}');
  actionpack (3.1.1) lib/action_view/path_set.rb:14:in `find'
```

需要增加相应的集成测试

**Comment by saberma** [comment]
已修正，增加相应集成测试
