### ISSUE TITLE
百科预览报错

### ISSUE THREAD

**Issue by saberma** [saberma/shopqi#201]
已保存时，编辑点击预览正常
未保存时，点击预览出现以下错误

``` html
RuntimeError in Wiki::WikiPagesController#preview

Called id for nil, which would mistakenly be 4 -- if you really wanted the id of nil, use object_id
Rails.root: /home/saberma/Documents/shopqi
```

``` ruby
/home/saberma/.rvm/gems/ruby-1.9.3-rc1/bundler/gems/gollum-e8df272729f4/lib/gollum/markup.rb:16:in `initialize'
/home/saberma/.rvm/gems/ruby-1.9.3-rc1/bundler/gems/gollum-e8df272729f4/lib/gollum/page.rb:187:in `new'
/home/saberma/.rvm/gems/ruby-1.9.3-rc1/bundler/gems/gollum-e8df272729f4/lib/gollum/page.rb:187:in `markup_class'
/home/saberma/.rvm/gems/ruby-1.9.3-rc1/bundler/gems/gollum-e8df272729f4/lib/gollum/page.rb:171:in `formatted_data'
app/controllers/wiki/wiki_pages_controller.rb:66:in `preview'
```

**Comment by liwh** [comment]
我这好像没问题啊,两个版本都看了，没发现问题

**Comment by saberma** [comment]
那我等下本地调试看看

**Comment by saberma** [comment]
最新版本没有问题
