### ISSUE TITLE
商店首页商品顺序在集合中手动排序不生效

### ISSUE THREAD

**Issue by saberma** [saberma/shopqi#231]
按标题拼音升序不成功，后台报错:

``` ruby
ActiveRecord::ReadOnlyRecord (ActiveRecord::ReadOnlyRecord):
  activerecord (3.1.1) lib/active_record/persistence.rb:293:in `create_or_update'
  activerecord (3.1.1) lib/active_record/callbacks.rb:264:in `block in create_or_update'
  activesupport (3.1.1) lib/active_support/callbacks.rb:408:in `_run_save_callbacks'
  activesupport (3.1.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  activerecord (3.1.1) lib/active_record/callbacks.rb:264:in `create_or_update'
  activerecord (3.1.1) lib/active_record/persistence.rb:37:in `save'
  activerecord (3.1.1) lib/active_record/validations.rb:50:in `save'
  activerecord (3.1.1) lib/active_record/attribute_methods/dirty.rb:22:in `save'
  activerecord (3.1.1) lib/active_record/transactions.rb:241:in `block (2 levels) in save'
  activerecord (3.1.1) lib/active_record/transactions.rb:295:in `block in with_transaction_returning_status'
  activerecord (3.1.1) lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
  activerecord (3.1.1) lib/active_record/transactions.rb:208:in `transaction'
  activerecord (3.1.1) lib/active_record/transactions.rb:293:in `with_transaction_returning_status'
  activerecord (3.1.1) lib/active_record/transactions.rb:241:in `block in save'
  activerecord (3.1.1) lib/active_record/transactions.rb:252:in `rollback_active_record_state!'
  activerecord (3.1.1) lib/active_record/transactions.rb:240:in `save'
  activerecord (3.1.1) lib/active_record/persistence.rb:133:in `update_attribute'
  app/controllers/admin/custom_collections_controller.rb:48:in `block in update_order'
```

要补充测试用例

**Comment by saberma** [comment]
无法按照价格排序，商品没有这个属性

**Comment by saberma** [comment]
多次排序会增加集合商品记录??待确认
原来是开两个窗口，分别将同一商品加入集合，则集合会包括两个重复的商品
属于低概率问题，不修正；如发生这个问题，仍可以手动删除重复记录

**Comment by saberma** [comment]
done
https://github.com/saberma/shopqi/commit/ed99a8a095a924ed683a490ba30e873c87b2dee2
