### ISSUE TITLE
bundle exec rake shopqi:bootstrap

### ISSUE THREAD

**Issue by apprentice1988** [saberma/shopqi#497]
bundle 中grit的问题才解决，这个命令又出错，请作者帮忙看一下，谢谢。
无论pg还是mysql，都会报这个错

```
undefined method `push' for LL("db"):Rake::Scope
/home/ji/.rvm/gems/ruby-1.9.2-p320/gems/seedbank-0.2.1/lib/seedbank/task_manager.rb:6:in `override_task'
/home/ji/.rvm/gems/ruby-1.9.2-p320/gems/seedbank-0.2.1/lib/seedbank/dsl.rb:10:in `override_seed_task'
/home/ji/.rvm/gems/ruby-1.9.2-p320/gems/seedbank-0.2.1/lib/tasks/seed.rake:32:in `block in <top (required)>'
/home/ji/.rvm/gems/ruby-1.9.2-p320@global/gems/rake-10.1.0/lib/rake/task_manager.rb:196:in `in_namespace'
/home/ji/.rvm/gems/ruby-1.9.2-p320@global/gems/rake-10.1.0/lib/rake/dsl_definition.rb:104:in `namespace'
/home/ji/.rvm/gems/ruby-1.9.2-p320/gems/seedbank-0.2.1/lib/tasks/seed.rake:1:in `<top (required)>'
/home/ji/.rvm/gems/ruby-1.9.2-p320/gems/activesupport-3.2.7/lib/active_support/dependencies.rb:245:in `load'
/home/ji/.rvm/gems/ruby-1.9.2-p320/gems/activesupport-3.2.7/lib/active_support/dependencies.rb:245:in `block in load'
/home/ji/.rvm/gems/ruby-1.9.2-p320/gems/activesupport-3.2.7/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/ji/.rvm/gems/ruby-1.9.2-p320/gems/activesupport-3.2.7/lib/active_support/dependencies.rb:245:in `load'
/home/ji/.rvm/gems/ruby-1.9.2-p320/gems/seedbank-0.2.1/lib/seedbank.rb:19:in `block in load_tasks'
/home/ji/.rvm/gems/ruby-1.9.2-p320/gems/seedbank-0.2.1/lib/seedbank.rb:19:in `each'
/home/ji/.rvm/gems/ruby-1.9.2-p320/gems/seedbank-0.2.1/lib/seedbank.rb:19:in `load_tasks'
/home/ji/.rvm/gems/ruby-1.9.2-p320/gems/seedbank-0.2.1/lib/seedbank/railtie.rb:9:in `block in <class:Railtie>'
/home/ji/.rvm/gems/ruby-1.9.2-p320/gems/railties-3.2.7/lib/rails/railtie.rb:184:in `instance_exec'
/home/ji/.rvm/gems/ruby-1.9.2-p320/gems/railties-3.2.7/lib/rails/railtie.rb:184:in `block in load_tasks'
/home/ji/.rvm/gems/ruby-1.9.2-p320/gems/railties-3.2.7/lib/rails/railtie.rb:184:in `each'
/home/ji/.rvm/gems/ruby-1.9.2-p320/gems/railties-3.2.7/lib/rails/railtie.rb:184:in `load_tasks'
/home/ji/.rvm/gems/ruby-1.9.2-p320/gems/railties-3.2.7/lib/rails/engine.rb:423:in `block in load_tasks'
/home/ji/.rvm/gems/ruby-1.9.2-p320/gems/railties-3.2.7/lib/rails/application/railties.rb:8:in `each'
/home/ji/.rvm/gems/ruby-1.9.2-p320/gems/railties-3.2.7/lib/rails/application/railties.rb:8:in `all'
/home/ji/.rvm/gems/ruby-1.9.2-p320/gems/railties-3.2.7/lib/rails/engine.rb:423:in `load_tasks'
/home/ji/.rvm/gems/ruby-1.9.2-p320/gems/railties-3.2.7/lib/rails/application.rb:145:in `load_tasks'
/home/ji/.rvm/gems/ruby-1.9.2-p320/gems/railties-3.2.7/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/ji/code/goodcode/shopqi/Rakefile:13:in `<top (required)>'
/home/ji/.rvm/gems/ruby-1.9.2-p320@global/gems/rake-10.1.0/lib/rake/rake_module.rb:25:in `load'
/home/ji/.rvm/gems/ruby-1.9.2-p320@global/gems/rake-10.1.0/lib/rake/rake_module.rb:25:in `load_rakefile'
/home/ji/.rvm/gems/ruby-1.9.2-p320@global/gems/rake-10.1.0/lib/rake/application.rb:637:in `raw_load_rakefile'
/home/ji/.rvm/gems/ruby-1.9.2-p320@global/gems/rake-10.1.0/lib/rake/application.rb:94:in `block in load_rakefile'
/home/ji/.rvm/gems/ruby-1.9.2-p320@global/gems/rake-10.1.0/lib/rake/application.rb:165:in `standard_exception_handling'
/home/ji/.rvm/gems/ruby-1.9.2-p320@global/gems/rake-10.1.0/lib/rake/application.rb:93:in `load_rakefile'
/home/ji/.rvm/gems/ruby-1.9.2-p320@global/gems/rake-10.1.0/lib/rake/application.rb:77:in `block in run'
/home/ji/.rvm/gems/ruby-1.9.2-p320@global/gems/rake-10.1.0/lib/rake/application.rb:165:in `standard_exception_handling'
/home/ji/.rvm/gems/ruby-1.9.2-p320@global/gems/rake-10.1.0/lib/rake/application.rb:75:in `run'
/home/ji/.rvm/gems/ruby-1.9.2-p320@global/gems/rake-10.1.0/bin/rake:33:in `<top (required)>'
/home/ji/.rvm/gems/ruby-1.9.2-p320/bin/rake:19:in `load'
/home/ji/.rvm/gems/ruby-1.9.2-p320/bin/rake:19:in `<main>'
/home/ji/.rvm/gems/ruby-1.9.2-p320/bin/ruby_noexec_wrapper:14:in `eval'
/home/ji/.rvm/gems/ruby-1.9.2-p320/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by i3zhe** [comment]
升级seedbank到0.3就可以

try use gem 'seedbank', github: 'james2m/seedbank' in Gemfile.

参考 https://github.com/james2m/seedbank/issues/27

**Comment by saberma** [comment]
thanks @i3zhe

**Comment by apprentice1988** [comment]
解决了，谢谢@i3zhe
